<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1738840492188' stop='1738840611516'>
    <name>Create Ticket via Opportunity</name>
    <title>Create Ticket via Opportunity</title>
    <test-cases>
        <test-case start='1738840492188' status='broken' stop='1738840611101'>
            <name>Opportunity Creation of Ticket</name>
            <title>Opportunity Creation of Ticket</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Timed out retrying after 20050ms: `cy.click()` failed because this element:
                
                `&lt;button aria-haspopup="true" data-drid="works--create-work-sidebar--shared-template-field-rev_org--account" class="focus:outline-none whitespace-nowrap disabled:bg-opacity-30 disabled:text-color-disabled text-color-secondary bg-button-tertiary font-medium border-0 border-transparent hover:text-color-primary hover:bg-button-tertiary-hovered focus:text-color-primary focus:bg-button-tertiary-hovered focus-visible:ring-1 focus-visible:ring-white-50 focus-visible:ring-offset-2 focus-visible:ring-offset-black-90 h-8 min-w-8 px-2 text-default sm-max:px-4 sm-max:py-3 sm-max:h-10 h-auto py-1.5 sm-max:h-auto sm-max:!py-1.5 !w-75 rounded-lg" type="button" aria-expanded="false">...&lt;/button>`
                
                is being covered by another element:
                
                `&lt;div class="text-color-primary whitespace-nowrap min-w-0" data-drid="don:core:dvrv-us-1:devo/118yxfjf3u:tag/1-label">Getting...&lt;/div>`
                
                Fix this problem, or use {force: true} to disable error checking.
                
                https://on.cypress.io/element-cannot-be-interacted-with</message>
                <stack-trace>CypressError: Timed out retrying after 20050ms: `cy.click()` failed because this element:
                
                `&lt;button aria-haspopup="true" data-drid="works--create-work-sidebar--shared-template-field-rev_org--account" class="focus:outline-none whitespace-nowrap disabled:bg-opacity-30 disabled:text-color-disabled text-color-secondary bg-button-tertiary font-medium border-0 border-transparent hover:text-color-primary hover:bg-button-tertiary-hovered focus:text-color-primary focus:bg-button-tertiary-hovered focus-visible:ring-1 focus-visible:ring-white-50 focus-visible:ring-offset-2 focus-visible:ring-offset-black-90 h-8 min-w-8 px-2 text-default sm-max:px-4 sm-max:py-3 sm-max:h-10 h-auto py-1.5 sm-max:h-auto sm-max:!py-1.5 !w-75 rounded-lg" type="button" aria-expanded="false">...&lt;/button>`
                
                is being covered by another element:
                
                `&lt;div class="text-color-primary whitespace-nowrap min-w-0" data-drid="don:core:dvrv-us-1:devo/118yxfjf3u:tag/1-label">Getting...&lt;/div>`
                
                Fix this problem, or use {force: true} to disable error checking.
                
                https://on.cypress.io/element-cannot-be-interacted-with
                    at ensureIsDescendent (https://app.devrev.ai/__cypress/runner/cypress_runner.js:111971:68)
                    at ensureDescendents (https://app.devrev.ai/__cypress/runner/cypress_runner.js:112022:5)
                    at ensureDescendentsAndScroll (https://app.devrev.ai/__cypress/runner/cypress_runner.js:112028:14)
                    at ensureElIsNotCovered (https://app.devrev.ai/__cypress/runner/cypress_runner.js:112159:5)
                    at runAllChecks (https://app.devrev.ai/__cypress/runner/cypress_runner.js:112358:52)
                    at retryActionability (https://app.devrev.ai/__cypress/runner/cypress_runner.js:112395:16)
                    at tryCatcher (https://app.devrev.ai/__cypress/runner/cypress_runner.js:1777:23)
                    at Promise.attempt.Promise.try (https://app.devrev.ai/__cypress/runner/cypress_runner.js:4285:29)
                    at whenStable (https://app.devrev.ai/__cypress/runner/cypress_runner.js:143474:68)
                    at &lt;unknown> (https://app.devrev.ai/__cypress/runner/cypress_runner.js:143415:14)
                    at tryCatcher (https://app.devrev.ai/__cypress/runner/cypress_runner.js:1777:23)
                    at Promise._settlePromiseFromHandler (https://app.devrev.ai/__cypress/runner/cypress_runner.js:1489:31)
                    at Promise._settlePromise (https://app.devrev.ai/__cypress/runner/cypress_runner.js:1546:18)
                    at Promise._settlePromise0 (https://app.devrev.ai/__cypress/runner/cypress_runner.js:1591:10)
                    at Promise._settlePromises (https://app.devrev.ai/__cypress/runner/cypress_runner.js:1671:18)
                    at Promise._fulfill (https://app.devrev.ai/__cypress/runner/cypress_runner.js:1615:18)
                    at &lt;unknown> (https://app.devrev.ai/__cypress/runner/cypress_runner.js:5420:46)
                From Your Spec Code:
                    at Object.proxyGetter [as get] (https://app.devrev.ai/__cypress/runner/cypress_runner.js:77891:22)
                    at exists (https://app.devrev.ai/__cypress/runner/cypress_runner.js:142674:26)
                    at elExists (https://app.devrev.ai/__cypress/runner/cypress_runner.js:142689:10)
                    at ensureExistence (https://app.devrev.ai/__cypress/runner/cypress_runner.js:142870:22)
                    at onFailFn (https://app.devrev.ai/__cypress/runner/cypress_runner.js:142899:53)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>