{
  "specName": "cypress\\e2e\\reportingTest\\preexceution.cy.js",
  "title": "passes",
  "suiteName": "pre exe",
  "testName": "pre exe passes",
  "testError": "Timed out retrying after 40000ms: The command was expected to run against origin `https://app.devrev.ai` but the application is at origin `https://passwordless.devrev.ai`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.\n\nUsing `cy.origin()` to wrap the commands run on `https://passwordless.devrev.ai` will likely fix this issue.\n\n`cy.origin('https://passwordless.devrev.ai', () => {`\n`  <commands targeting https://passwordless.devrev.ai go here>`\n`})`",
  "testCommands": [
    "visit https://app.devrev.ai/test-demo1",
    "get input[inputmode=\"email\"]",
    "request ",
    "request ",
    "request ",
    "request ",
    "request ",
    "request ",
    "request ",
    "request ",
    "request ",
    "request ",
    "request ",
    "request ",
    "page load --waiting for new page to load--",
    "request ",
    "request ",
    "request ",
    "request ",
    "new url https://passwordless.devrev.ai/login?state=hKFo2SB0NzJDX2RFWUJTYjVwdDRpaDNaYlVaSHhlQ0RPTDJLUaFupWxvZ2luo3RpZNkgaEdQdndGZTlnYzljNW5FWkdVaXl0QXBrSk5ac0xfQkKjY2lk2SB1VG9Bbkd1RDI0TTVyOEJSTERObFo4cUFXY0cxb1pDbw&client=uToAnGuD24M5r8BRLDNlZ8qAWcG1oZCo&protocol=oauth2&prompt=select_account&scope=openid%20profile%20email&response_type=code&redirect_uri=https%3A%2F%2Fauth.devrev.ai%2Flogin%2Fcallback&response_mode=query",
    "request "
  ]
}
